# This is a basic workflow to help you get started with Actions

name: Fetch Blacklisted Contests

# Controls when the workflow will run
on:
  # Runs cron job
  schedule:
    - cron: '0 0 15 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      scripts-dir: ./scripts

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      # Runs a set of commands using the runners shell
      - name: Install python dependencies
        run: python -m pip install -r requirements.txt
        working-directory: ${{env.scripts-dir}}
      - name: Run script
        run: |
          if python3 ${{ env.scripts-dir }}/get_contests.py; then
            git config user.name "Github Actions Bot"
            git config user.email "<>"
            git add contests.json
            git commit -m "blacklisted contests added"
            git push
            curl -X POST https://api.github.com/repos/geekypandey/cf_tracker/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            -u ${{ secrets.ACCESS_TOKEN }} \
            --data '{"event_type": "deploy", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          fi
        env:
          TRY_BLACKLISTED: 1

